# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/website

    environment:

    steps:
      - checkout
      - setup_remote_docker
      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      # run tests!
      - run: npm install
      # Build docker image
      - run: docker build -t $DOCKER_REPOSITORY/website:$CIRCLE_BUILD_NUM .
      # Run docker container
      - run: docker run -d -p 3000:3000 --name website $DOCKER_REPOSITORY/website:$CIRCLE_BUILD_NUM
      # Test docker image
      - run: sleep 20 && docker exec website curl --retry 10 http://localhost:3000/
      # Tagging Image with dynamic tag
      - run: docker tag $DOCKER_REPOSITORY/website:$CIRCLE_BUILD_NUM $DOCKER_REPOSITORY/website:latest
      # docker login
      - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      # Push docker image to docker registry
      - run: docker push $DOCKER_REPOSITORY/website:$CIRCLE_BUILD_NUM
      - run: docker push $DOCKER_REPOSITORY/website:latest